# Generated by Django 6.0.2 on 2026-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productedithistory',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
